### PR TITLE
Run FastBoot server in tests with `ember serve`

### LINKED ISSUE #96: `stopServer` doesn't wait for exit
It sends the kill signal, then resolves the promise. It doesn't wait for exit.

https://github.com/tomdale/ember-cli-addon-tests/blob/fd1ef7f9506f4667d08532100511b1d4de919b3c/lib/models/app.js#L49-L52

It's only an issue in Unix, and only an issue in ember-cli 2.13. I've tried to fix it, but none of the events that I expect to fire are firing.

Failing test: #95

### PR DESCRIPTION
**Pull request by simonihmig**
`ember fastboot --serve-assets` is deprecated with newest version of ember-cli-fastboot.

Also this _might_ fix #96

### CODE REVIEW

File: test/acceptance/application-test.js [hunk 1]
```diff
@@ -56,18 +56,24 @@ describe('Acceptance | application', function() {
...
   });
 
   it('works', function() {
-    return request('http://localhost:49741')
+    return request({
+      url: 'http://localhost:49741',
+      headers: {
+        // We have to send the `Accept` header so the ember-cli server sees this as a request to `index.html` and sets
+        // `req.serveUrl`, that ember-cli-fastboot needs in its middleware
+        // See https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/middleware/history-support/index.js#L55
```
Comment (kellyselden) [inline test/acceptance/application-test.js]: Can you link to commits here instead of master, as the line numbers will gradually drift.

Comment (simonihmig) [inline test/acceptance/application-test.js]: @kellyselden makes sense, done!
